import React from "react";
import { Link } from "react-router-dom";

/**
 * Customer Referral Program Terms — includes standard Refer & Earn rewards
 * and the limited New Customer 365-Day CraveMore Free Delivery promotion.
 */
const ReferralProgramTermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-xl mx-auto px-4 py-6 pb-24">
        <h1 className="text-2xl font-bold mb-2">Crave’n Referral Program Terms</h1>
        <p className="text-sm text-muted-foreground mb-2">
          Last updated: July 22, 2026 · Terms version: Referral v1 / Promo terms v1
        </p>
        <p className="text-sm text-muted-foreground mb-6">
          These Referral Program Terms (“Referral Terms”) supplement the{" "}
          <Link to="/legal/terms" className="text-orange-600 underline font-medium">
            Crave’n Terms of Service
          </Link>{" "}
          and, where applicable, the{" "}
          <Link to="/legal/cravemore" className="text-orange-600 underline font-medium">
            CraveMore Subscription Terms
          </Link>
          . By using Refer & Earn, sharing a referral code or link, or participating in a referral
          promotion, you agree to these Referral Terms.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">1. Overview</h2>
        <p className="text-sm mb-4">
          Crave’n’s customer referral program (“Refer & Earn”) lets eligible customers invite new
          customers to Crave’n using a personal referral code and invite link. When a referred friend
          completes the qualification requirements described in the app and these Referral Terms, Crave’n
          may issue referral rewards (such as account credits) under the standard program. From time to
          time, Crave’n may also offer limited additional promotions layered on the same referral system,
          including the New Customer 365-Day CraveMore Free Delivery promotion described in Section 8.
        </p>
        <p className="text-sm mb-4">
          Refer & Earn is not a separate parallel referral system. There is one referral code and one
          invite link per eligible customer account. Promotional prizes, when offered, use that same
          code and link and the same underlying referral records.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">2. Eligibility</h2>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>You must have an active Crave’n customer account in good standing.</li>
          <li>
            You must be at least 18 years old and located in a geographic area where Crave’n offers the
            Services.
          </li>
          <li>
            Employees, contractors, and test accounts may be excluded from rewards at Crave’n’s
            discretion.
          </li>
          <li>
            Crave’n may limit, suspend, or deny participation where fraud, abuse, or policy violations
            are suspected.
          </li>
        </ul>

        <h2 className="text-lg font-semibold mt-6 mb-2">3. Referral Codes and Invite Links</h2>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            Each eligible customer receives one permanent personal referral code generated by Crave’n.
            Codes do not change once issued for that account.
          </li>
          <li>
            Your invite link is associated with that same code (for example, a link using your code).
            Sharing either the code or the link attributes referrals to your account when Crave’n’s
            systems successfully record the attribution.
          </li>
          <li>
            You may share your code or link through the in-app share tools (such as copy, email, or text)
            or other lawful personal sharing. You may not purchase ads, spam, misrepresent Crave’n, or
            use deceptive practices to obtain referrals.
          </li>
          <li>
            Crave’n does not create a second referral code solely for promotional campaigns. Prize
            progress, when applicable, is tied to your existing code and link.
          </li>
        </ul>

        <h2 className="text-lg font-semibold mt-6 mb-2">4. How Standard Referral Rewards Work</h2>
        <p className="text-sm mb-2">Typically, to earn a standard referral reward:</p>
        <ol className="list-decimal pl-5 text-sm space-y-1 mb-4">
          <li>You share your referral code or invite link with someone who is new to Crave’n.</li>
          <li>
            The friend creates a new eligible Crave’n customer account using your code or link so the
            referral can be attributed.
          </li>
          <li>
            The friend places a qualifying first order that meets the minimum order amount and other
            requirements shown in the app (requirements are configurable and may change).
          </li>
          <li>
            After the order is completed/delivered and Crave’n’s systems mark the referral as qualified
            or completed, referral rewards may issue automatically.
          </li>
        </ol>
        <p className="text-sm mb-4">
          Pending, rejected, refunded, reversed, fraudulent, or incomplete referrals do not qualify for
          rewards. Self-referrals and referrals between accounts controlled by the same person are not
          allowed.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">5. Standard Reward Amounts and Credits</h2>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            Reward amounts for you (the referrer) and your friend (the referred customer) are shown in
            the Refer & Earn experience and may vary by account type, membership status, geography, or
            promotion. Illustrative amounts in the app (for example, credits for you and an offer for
            your friend, or boosted amounts for active CraveMore members) are not guaranteed and may be
            updated.
          </li>
          <li>
            Unless otherwise stated, standard rewards are issued as Crave’n account credits or
            promotional balances, not cash. Credits cannot be withdrawn, transferred for cash value, or
            sold.
          </li>
          <li>
            Credits apply only to eligible Crave’n orders and may exclude tips, certain fees, gift cards,
            or other categories as disclosed at redemption or checkout.
          </li>
          <li>
            Generally, one standard referral reward applies per new referred customer who successfully
            qualifies. Duplicate accounts for the same person do not create multiple rewards.
          </li>
          <li>
            Active CraveMore members may receive boosted standard referral rewards when that feature is
            enabled; boosted amounts remain subject to these Referral Terms and CraveMore rules.
          </li>
        </ul>

        <h2 className="text-lg font-semibold mt-6 mb-2">6. Qualification, Tracking, and Timing</h2>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            Qualification is determined by Crave’n’s backend systems using referral records (including
            status values such as pending, completed, or paid, and whether requirements are met). The
            client app cannot mark a referral as qualified or issue rewards on its own.
          </li>
          <li>
            Reward activity may appear in areas such as My Credits / reward activity views. Display
            timing can vary while orders settle or reviews complete.
          </li>
          <li>
            Crave’n may delay, withhold, or reverse rewards if an order is canceled, refunded, charged
            back, flagged for fraud, or otherwise fails to remain a valid qualifying order.
          </li>
        </ul>

        <h2 className="text-lg font-semibold mt-6 mb-2">7. Prohibited Conduct and Anti-Fraud</h2>
        <p className="text-sm mb-2">You agree not to:</p>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>Refer yourself, create fake or duplicate accounts, or use the same phone, email, device, or payment method to manufacture referrals</li>
          <li>Engage in referral loops, collusion, or coordinated abuse</li>
          <li>Use bots, scripts, or automated sharing that violates platform rules</li>
          <li>Misrepresent rewards, Crave’n, or eligibility to friends</li>
          <li>Attempt to manipulate qualification, progress counts, or promotional prizes through the client app or other unauthorized means</li>
        </ul>
        <p className="text-sm mb-4">
          Crave’n may investigate activity, disqualify referrals or promotions, claw back credits where
          permitted by law, suspend accounts, and share information with payment processors or law
          enforcement when appropriate. Internal fraud-detection details are not disclosed to customers.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">
          8. Limited Promotion: New Customer 365 Days of CraveMore Free Delivery
        </h2>
        <p className="text-sm mb-2">
          Crave’n may offer a limited promotional prize (“365 Promotion”) with the internal campaign key{" "}
          <span className="font-medium">new_customer_365_cravemore_referral_promotion</span> and
          customer-facing title such as “Refer Friends. Earn 365 Days of Free Delivery.” The 365
          Promotion is an <span className="font-medium">additional</span> incentive layered on the
          existing Refer & Earn program. It does not replace standard referral credits.
        </p>

        <h3 className="text-base font-semibold mt-4 mb-2">8.1 What you can win</h3>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            Upon successful completion, an eligible participant may receive{" "}
            <span className="font-medium">365 consecutive days</span> of CraveMore benefits under a
            promotional membership entitlement (membership source such as{" "}
            <span className="font-medium">new_customer_referral_365_promo</span>).
          </li>
          <li>
            During an active promotional entitlement, eligible delivery fees may be $0 on orders that
            meet CraveMore benefit rules then in effect (including minimum subtotal, merchant
            eligibility, and service-area rules). Taxes, tips, service fees, express fees, and other
            charges not covered by CraveMore remain payable.
          </li>
          <li>
            The promotional entitlement does <span className="font-medium">not</span> automatically renew
            as a paid CraveMore subscription unless you separately enroll and authorize paid billing
            under the CraveMore Subscription Terms.
          </li>
        </ul>

        <h3 className="text-base font-semibold mt-4 mb-2">8.2 Who can earn the 365 prize</h3>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            The 365 Promotion is generally limited to{" "}
            <span className="font-medium">eligible new Crave’n customers</span> whose customer account
            was created during the promotional account-eligibility window configured by Crave’n.
          </li>
          <li>
            You must not have already received this promotional reward (maximum typically one reward per
            customer per promotion).
          </li>
          <li>
            You must be in an eligible service area, keep your account in good standing, and satisfy
            standard referral program rules.
          </li>
          <li>
            Eligibility is confirmed by Crave’n’s servers. The app cannot grant eligibility, increase
            your qualifying count, or issue the prize by itself.
          </li>
          <li>
            Existing customers outside the new-customer window continue to use standard Refer & Earn but
            do not automatically earn the 365 prize unless Crave’n expressly configures otherwise.
          </li>
          <li>
            Enrollment for eligible customers is automatic when Crave’n evaluates eligibility (for
            example at account creation or when opening Refer & Earn). No separate signup form is
            required.
          </li>
        </ul>

        <h3 className="text-base font-semibold mt-4 mb-2">8.3 How you earn the 365 prize</h3>
        <ol className="list-decimal pl-5 text-sm space-y-1 mb-4">
          <li>Open Refer & Earn and share your existing prize invite code or invite link.</li>
          <li>
            Friends who are new to Crave’n sign up through your code/link and complete qualifying first
            orders under the standard referral qualification rules.
          </li>
          <li>
            Each referral that reaches a qualifying completed/paid status in Crave’n’s referral records,
            within the promotion’s qualification period, and that is not rejected, reversed, refunded, or
            fraud-flagged, may count as one qualifying referral toward the 365 prize.
          </li>
          <li>
            When your qualifying referral count reaches the required number configured for the campaign
            (displayed in the app; default configuration may be five), Crave’n revalidates eligibility and
            may issue the 365-day CraveMore promotional entitlement.
          </li>
        </ol>
        <p className="text-sm mb-4">
          The same qualifying referral may count toward both a standard referral credit and 365 prize
          progress when it satisfies the rules for both. Progress is calculated from existing referral
          records; the same referral is not counted twice toward the same promotion, and the prize is
          issued only once.
        </p>

        <h3 className="text-base font-semibold mt-4 mb-2">8.4 Deadlines</h3>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            <span className="font-medium">Account eligibility window:</span> when your account must have
            been created to enroll as a new-customer participant.
          </li>
          <li>
            <span className="font-medium">Campaign / marketing window:</span> when the promotion is
            publicly active.
          </li>
          <li>
            <span className="font-medium">Referral completion deadline:</span> by when you must finish the
            required qualifying referrals. You may have time after joining to finish referrals even if
            public marketing ends, as configured in the campaign.
          </li>
        </ul>
        <p className="text-sm mb-4">
          Exact dates are controlled in Crave’n’s promotion configuration and may be shown in the app.
          Failure to meet the completion deadline may cause the prize opportunity to expire for that
          account.
        </p>

        <h3 className="text-base font-semibold mt-4 mb-2">8.5 Membership stacking</h3>
        <p className="text-sm mb-4">
          If you already have an active CraveMore trial, paid subscription, or other membership when the
          365 prize is earned, Crave’n’s stacking policy applies. The default implemented behavior is to{" "}
          <span className="font-medium">queue</span> the 365-day promotional entitlement to begin after
          the current active membership period ends, without shortening or overwriting your existing
          Stripe/paid membership record. Checkout recognizes an active promotional entitlement using the
          same CraveMore benefit calculation rules as an active membership for eligible delivery-fee
          waiver purposes.
        </p>

        <h3 className="text-base font-semibold mt-4 mb-2">8.6 Reversals after progress or issuance</h3>
        <ul className="list-disc pl-5 text-sm space-y-1 mb-4">
          <li>
            If a referral that counted toward the 365 prize is later reversed before the prize is issued,
            Crave’n recalculates progress and may reduce your qualifying count.
          </li>
          <li>
            After the prize is issued, Crave’n follows its referral and promotional reversal policies.
            An active 365-day entitlement is not automatically removed solely because of a later reversal
            unless approved business rules require it; records may be flagged for review.
          </li>
        </ul>

        <h3 className="text-base font-semibold mt-4 mb-2">8.7 Prize status displays</h3>
        <p className="text-sm mb-4">
          The app may show statuses such as eligible, in progress, completed, reward pending, reward
          active, expired, or disqualified. Informational messaging for customers who are not enrolled
          does not create a right to the prize.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">9. Relationship to CraveMore Paid Subscriptions</h2>
        <p className="text-sm mb-4">
          Promotional CraveMore entitlements earned through referrals are distinct from paid CraveMore
          subscriptions. Paid plans, trials that convert to paid billing, cancellations, and price changes
          remain governed by the CraveMore Subscription Terms. Winning the 365 prize does not require you
          to start a paid subscription, and expiration of the prize does not by itself enroll you in paid
          auto-renewal.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">10. Taxes</h2>
        <p className="text-sm mb-4">
          You are responsible for any taxes that may apply to referral rewards or promotional benefits
          under applicable law. Crave’n may report rewards where required.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">11. Changes, Suspension, and Termination</h2>
        <p className="text-sm mb-4">
          Crave’n may modify, pause, or end Refer & Earn, reward amounts, qualification rules, or any
          layered promotion (including the 365 Promotion) at any time, prospectively, to the extent
          permitted by law. Material updates to these Referral Terms will be reflected by updating the
          “Last updated” date and, where appropriate, in-app notice. Continued use of Refer & Earn after
          changes means you accept the updated Referral Terms. Crave’n may also terminate your
          participation for violations of these Referral Terms or the Terms of Service.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">12. No Cash Value; Non-Transferability</h2>
        <p className="text-sm mb-4">
          Unless required by law, referral credits and promotional CraveMore entitlements have no cash
          value, are non-transferable, and may not be sold, bartered, or assigned. Unused benefits may
          expire according to their stated duration or program rules.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">13. Disclaimers</h2>
        <p className="text-sm mb-4">
          Referral rewards and promotions are provided as-is. Crave’n does not guarantee that any
          particular friend will qualify, that attribution will succeed in every share method, that
          delivery fees will be $0 on every order during a promotional CraveMore period, or that the
          program will remain available indefinitely.
        </p>

        <h2 className="text-lg font-semibold mt-6 mb-2">14. Contact</h2>
        <p className="text-sm mb-1 font-medium">Crave’n Inc.</p>
        <p className="text-sm">Email: help@cravenusa.com</p>
        <p className="text-sm mb-6">Phone: 216-435-0821</p>

        <p className="text-xs text-muted-foreground">
          Related:{" "}
          <Link to="/legal/terms" className="underline">
            Terms of Service
          </Link>
          {" · "}
          <Link to="/legal/cravemore" className="underline">
            CraveMore Terms
          </Link>
          {" · "}
          <Link to="/invite-friends" className="underline">
            Refer & Earn
          </Link>
        </p>
      </div>
    </div>
  );
};

export default ReferralProgramTermsPage;
