import DOMPurify from 'dompurify';

/**
 * DOMPurify's default profile strips <style>, which makes stored legal templates look like plain text.
 * These documents are generated by our edge functions / templates (trusted); we allow inline styles
 * and <style> blocks so certificate / resolution / bylaws formatting renders.
 */
const SANITIZE_CONFIG: DOMPurify.Config = {
  WHOLE_DOCUMENT: true,
  ADD_TAGS: ['style', 'meta', 'title', 'head', 'html', 'body'],
  ADD_ATTR: ['style', 'class', 'id', 'charset', 'name', 'content', 'lang', 'href', 'src', 'alt', 'width', 'height', 'border', 'cellpadding', 'cellspacing', 'colspan', 'rowspan', 'align', 'valign'],
};

export function sanitizeExecutiveDocumentHtml(html: string): string {
  if (!html || !html.trim()) {
    return '<!DOCTYPE html><html><head><meta charset="utf-8"/></head><body><p>Empty document</p></body></html>';
  }
  const sanitized = DOMPurify.sanitize(html.trim(), SANITIZE_CONFIG);
  // iframe srcDoc should be a full document; fragments are wrapped
  if (/<!DOCTYPE/i.test(sanitized) || /<html[\s>]/i.test(sanitized)) {
    return sanitized;
  }
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/></head><body>${sanitized}</body></html>`;
}
