-- Create new regions for random US cities
INSERT INTO regions (name, zip_prefix, status) VALUES
('Atlanta, GA', '303', 'active'),
('Chicago, IL', '606', 'active'),
('Houston, TX', '770', 'active'),
('Phoenix, AZ', '850', 'active'),
('Philadelphia, PA', '191', 'active'),
('San Antonio, TX', '782', 'active'),
('Dallas, TX', '752', 'active'),
('Austin, TX', '787', 'active'),
('Jacksonville, FL', '322', 'active'),
('Charlotte, NC', '282', 'active'),
('Indianapolis, IN', '462', 'active'),
('Denver, CO', '802', 'active'),
('Nashville, TN', '372', 'active'),
('Memphis, TN', '381', 'active'),
('Louisville, KY', '402', 'active'),
('Milwaukee, WI', '532', 'active'),
('Las Vegas, NV', '891', 'active'),
('Baltimore, MD', '212', 'active'),
('St. Louis, MO', '631', 'active'),
('Tampa, FL', '336', 'active'),
('Pittsburgh, PA', '152', 'active'),
('Sacramento, CA', '958', 'active'),
('Miami, FL', '331', 'active'),
('Minneapolis, MN', '554', 'active'),
('Raleigh, NC', '276', 'active'),
('New Orleans, LA', '701', 'active'),
('Richmond, VA', '232', 'active'),
('Birmingham, AL', '352', 'active'),
('Oklahoma City, OK', '731', 'active'),
('Hartford, CT', '061', 'active'),
('Salt Lake City, UT', '841', 'active'),
('Omaha, NE', '681', 'active')
ON CONFLICT DO NOTHING;